# Generated by Django 5.0 on 2025-12-03 09:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('certificate', 'Birth Certificate'), ('pedigree', 'Pedigree'), ('registration', 'Registration Papers'), ('medical', 'Medical Records'), ('purchase', 'Purchase Agreement'), ('insurance', 'Insurance Documents'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='animals/documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='animals/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('pig', 'Pig'), ('poultry', 'Poultry')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('average_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('average_lifespan', models.PositiveIntegerField(blank=True, help_text='In years', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['species', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tag_id', models.CharField(help_text='Unique identification tag', max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/photos/')),
                ('microchip_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('location', models.CharField(help_text='Pen/Paddock/Barn location', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='Dairy, Meat, Breeding, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_mother', to='animals.animal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
