# Generated by Django 5.0 on 2025-12-03 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_father', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animaldocument',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animaldocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalphoto',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animalphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalweight',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animalweight',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['species'], name='animals_bre_species_413375_idx'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['name'], name='animals_bre_name_ef88bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('name', 'species')},
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.breed'),
        ),
        migrations.AddIndex(
            model_name='animalweight',
            index=models.Index(fields=['animal', '-measured_at'], name='animals_ani_animal__baf6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['owner', 'status'], name='animals_ani_owner_i_081c74_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tag_id'], name='animals_ani_tag_id_5fbaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['breed'], name='animals_ani_breed_i_2a59b4_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['health_status'], name='animals_ani_health__f7c454_idx'),
        ),
    ]
