# Generated by Django 5.0 on 2025-12-03 18:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('checkup', 'General Checkup'), ('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('surgery', 'Surgery'), ('injury', 'Injury'), ('illness', 'Illness'), ('test', 'Laboratory Test'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptoms')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °F', max_digits=4, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('treatment_provided', models.TextField(blank=True)),
                ('medications', models.JSONField(blank=True, default=list, help_text='List of medications')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('veterinarian', models.CharField(blank=True, max_length=200)),
                ('veterinarian_license', models.CharField(blank=True, max_length=100)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('vaccination_due', 'Vaccination Due'), ('checkup_due', 'Checkup Due'), ('treatment_due', 'Treatment Due'), ('follow_up', 'Follow-up Required'), ('abnormal_vitals', 'Abnormal Vitals'), ('weight_loss', 'Weight Loss'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('alert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='animals.animal')),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='health_records.healthrecord')),
            ],
            options={
                'ordering': ['-alert_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('fecal', 'Fecal Test'), ('biopsy', 'Biopsy'), ('xray', 'X-Ray'), ('ultrasound', 'Ultrasound'), ('other', 'Other')], max_length=20)),
                ('test_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('results_file', models.FileField(blank=True, null=True, upload_to='health_records/lab_results/')),
                ('interpretation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_normal', models.BooleanField(blank=True, null=True)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample_collected_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('laboratory_name', models.CharField(blank=True, max_length=200)),
                ('technician_name', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='animals.animal')),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='health_records.healthrecord')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('three_times_daily', 'Three Times Daily'), ('weekly', 'Weekly'), ('as_needed', 'As Needed')], max_length=20)),
                ('administration_route', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('instructions', models.TextField(help_text='Administration instructions')),
                ('side_effects', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prescribed_by', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='animals.animal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='health_records.healthrecord')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('disease_target', models.CharField(help_text='Disease being prevented', max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('administration_route', models.CharField(help_text='e.g., Intramuscular, Subcutaneous', max_length=100)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('administered_by', models.CharField(blank=True, max_length=200)),
                ('veterinarian', models.CharField(blank=True, max_length=200)),
                ('adverse_reactions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='health_records.healthrecord')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['animal', '-visit_date'], name='health_reco_animal__ac1b46_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['record_type'], name='health_reco_record__5e2ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['priority'], name='health_reco_priorit_b2591c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['is_resolved'], name='health_reco_is_reso_893eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['animal', '-alert_date'], name='health_reco_animal__a21b37_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['severity'], name='health_reco_severit_43415e_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['is_resolved'], name='health_reco_is_reso_f60056_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['animal', '-requested_date'], name='health_reco_animal__0fd9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['test_type'], name='health_reco_test_ty_b91ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status'], name='health_reco_status_6fad6e_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['animal', '-start_date'], name='health_reco_animal__5e9b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['status'], name='health_reco_status_91f4da_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['animal', '-scheduled_date'], name='health_reco_animal__2670b3_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['status'], name='health_reco_status_117e62_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['next_due_date'], name='health_reco_next_du_511ebb_idx'),
        ),
    ]
